function preset = gps_presets(name)
% Returns preset variables.
%
% Author: Alexander Conrad Nied (anied@cs.washington.edu)
%
% Changelog:
% 2014-01-02 Automatically generated by gps_init to format GPS
%
% GPS is a GUI-based program composed by David Gow and members of his lab
% at the Massachusetts General Hospital to automate MNE and FSL analyses
% of MR-constrained MEG/EEG data and to perform Kalman filter based Granger
% analyses of those data.
%
% Copyright (C) 2014  Alexander Conrad Nied and David Gow
% 
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.

switch lower(name)
    case {'gpsnum', 'gpsfig', 'menu figure'}
        preset = 6750000;
    case {'gpsanum', 'gpsafig', 'analysis figure'}
        preset = 6754000;
    case {'gpsenum', 'gpsefig', 'edit figure'}
        preset = 6753000;
    case {'gpsrnum', 'gpsrfig', 'region figure'}
        preset = 6752000;
    case {'gpspnum', 'gpspfig', 'plotting figure'}
        preset = 6757000;
    case {'dir', 'directory'}
        preset = '/Users/tomfool/tech/19/gow/GPS';
        % preset = '/autofs/cluster/dgow/GPS1.9/GPS';
    case {'functions', 'functiondir', 'fdir'}
        preset = '/Users/tomfool/tech/19/gow/GPS/functions';
        % preset = '/autofs/cluster/dgow/GPS1.9/GPS/functions';
    case {'parameters', 'parameterdir', 'pdir'}
        preset = '/Users/tomfool/tech/19/gow/GPS/parameters';
        % preset = '/autofs/cluster/dgow/GPS1.9/GPS/parameters';
    case {'images', 'imagedir', 'idir'}
        preset = '/Users/tomfool/tech/19/gow/GPS/images';
        % preset = '/autofs/cluster/dgow/GPS1.9/GPS/images';
    case {'logs', 'logdir', 'ldir'}
        preset = '/Users/tomfool/tech/19/gow/GPS/logs';
        % preset = '/autofs/cluster/dgow/GPS1.9/GPS/logs';
    case {'study'}
        preset = 'SampleStudy';
    case {'stages'}
        preset = {'util', 'mri', 'meg', 'mne', 'granger'};
        %preset = {'util', 'mri', 'meg', 'mne', 'plv', 'granger'};
    case {'stagenames'}
        preset = {'Utilities', 'MRI', 'MEG', 'MNE', 'Granger'};
        %preset = {'Utilities', 'MRI', 'MEG', 'MNE', 'PLV', 'Granger'};
end % switch

end % function
