function gpsr_menu_init
% Initializes the Menu for GPSr
%
% Author: A. Conrad Nied
%
% Changelog:
% 2013.05.31 - Made based on GPS1.8/gpsa_init_fig.m
% 2013.06.03 - Fleshed out more
% 2013.06.07 - Added Cortex options and made code more visually appealling

%% Get parameters and set some presets

bg_color = [0.8 0.8 0.8];
state = gpsr_get;
state.position.menu     = [100, state.position.screen(4) - 100, 160, 520];
state.position.features = [ 20,   state.position.menu(4) - 210, 120, 160];
state.position.panel    = [ 20,                             20, 120, 280];

    function pos = panel_item_pos(horz_offset_fraction, vert_offset, width_fraction, height)
        pos(1) = (state.position.panel(3) - 20) * horz_offset_fraction + 10;
        pos(2) = state.position.panel(4) - 20 - height - vert_offset;
        pos(3) = (state.position.panel(3) - 20) * width_fraction;
        pos(4) = height;
    end

%% Draw the main GUI figure and set properties
clf(state.menu.fig)
set(state.menu.fig, 'Visible', 'on',...
    'Units', 'pixels', 'Position', state.position.menu,...
    'Color', bg_color,...
    'ToolBar', 'none', 'NumberTitle', 'off',...
    'Name', 'GPSr');

% Draw the title
state.menu.title = uicontrol(state.menu.fig, 'Style', 'Text',...
    'Units', 'pixels', 'Position', [20, state.position.menu(4) - 40, state.position.menu(3) - 40, 25],...
    'BackgroundColor', bg_color, 'FontSize', 14,...
    'String', 'GPS: Regions', 'HorizontalAlignment', 'center');

%% Draw the primary panel

% Panel
state.menu.features.panel = uipanel(state.menu.fig,...
    'Units', 'pixels', 'Position', state.position.features,...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Title', 'Features');

% Cortex
state.menu.features.cortex = uicontrol(state.menu.features.panel,...
    'Units', 'pixels', 'Position', [10, 110, 100, 25],...
    'BackgroundColor', bg_color, 'FontSize', 12,...
    'Style', 'ToggleButton', 'String', 'Cortex',...
    'Callback', 'gpsr_menu_panel(''cortex'');');

% Timecourses
state.menu.features.timecourses = uicontrol(state.menu.features.panel,...
    'Units', 'pixels', 'Position', [10, 85, 100, 25],...
    'BackgroundColor', bg_color, 'FontSize', 12,...
    'Style', 'ToggleButton', 'String', 'Timecourses',...
    'Callback', 'gpsr_menu_panel(''timecourses'');');

% Overlays
state.menu.features.overlays = uicontrol(state.menu.features.panel,...
    'Units', 'pixels', 'Position', [10, 60, 100, 25],...
    'BackgroundColor', bg_color, 'FontSize', 12,...
    'Style', 'ToggleButton', 'String', 'Overlays',...
    'Callback', 'gpsr_menu_panel(''overlays'');');

% Centroids
state.menu.features.centroids = uicontrol(state.menu.features.panel,...
    'Units', 'pixels', 'Position', [10, 35, 100, 25],...
    'BackgroundColor', bg_color, 'FontSize', 12,...
    'Style', 'ToggleButton', 'String', 'Centroids',...
    'Callback', 'gpsr_menu_panel(''centroids'');');

% Regions
state.menu.features.regions = uicontrol(state.menu.features.panel,...
    'Units', 'pixels', 'Position', [10, 10, 100, 25],...
    'BackgroundColor', bg_color, 'FontSize', 12,...
    'Style', 'ToggleButton', 'String', 'Regions',...
    'Callback', 'gpsr_menu_panel(''regions'');');

%% Cortex Panel

% Panel
state.menu.cortex.panel = uipanel(state.menu.fig,...
    'Units', 'pixels', 'Position', state.position.panel,...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Title', 'Cortex');

% Study list
state.menu.cortex.study = uicontrol(state.menu.cortex.panel,...
    'Units', 'pixels', 'Position', panel_item_pos(0, 0, 1, 22),...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Style', 'popupmenu',...
    'String', 'STUDY01',...
    'Value', 1,...
    'Callback', 'gpsr_menu_cortex');

% Subject list
state.menu.cortex.subject = uicontrol(state.menu.cortex.panel,...
    'Units', 'pixels', 'Position', panel_item_pos(0, 25, 1, 22),...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Style', 'popupmenu',...
    'String', 'STUDY01_01',...
    'Value', 1,...
    'Callback', 'gpsr_menu_cortex');

% Left
state.menu.cortex.left = uicontrol(state.menu.cortex.panel,...
    'Units', 'pixels', 'Position', panel_item_pos(0, 50, 0.475, 22),...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Style', 'ToggleButton',...
    'String', 'Left',...
    'Value', 1,...
    'Callback', 'gpsr_menu_cortex');

% Right
state.menu.cortex.right = uicontrol(state.menu.cortex.panel,...
    'Units', 'pixels', 'Position', panel_item_pos(0.525, 50, 0.475, 22),...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Style', 'ToggleButton',...
    'String', 'Right',...
    'Value', 0,...
    'Callback', 'gpsr_menu_cortex');

% Surface list
state.menu.cortex.subject = uicontrol(state.menu.cortex.panel,...
    'Units', 'pixels', 'Position', panel_item_pos(0, 75, 1, 22),...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Style', 'popupmenu',...
    'String', {'inflated', 'orig', 'pial', 'smoothwm', 'sphere', 'white'},...
    'Value', 1,...
    'Callback', 'gpsr_menu_cortex');

% Perspective list
state.menu.cortex.perspective = uicontrol(state.menu.cortex.panel,...
    'Units', 'pixels', 'Position', panel_item_pos(0, 100, 1, 22),...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Style', 'popupmenu',...
    'String', {'Lateral', 'Medial', 'Frontal', 'Occipital', 'Dorsal', 'Ventral', 'Lat & Med', 'Free Rotate'},...
    'Value', 1,...
    'Callback', 'gpsr_menu_cortex');

% Atlas list
state.menu.cortex.atlas = uicontrol(state.menu.cortex.panel,...
    'Units', 'pixels', 'Position', panel_item_pos(0, 125, 1, 22),...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Style', 'popupmenu',...
    'String', {'No Atlas', 'aparc'},...
    'Value', 1,...
    'Callback', 'gpsr_menu_cortex');

% Darken Sulci
state.menu.cortex.sulci = uicontrol(state.menu.cortex.panel,...
    'Units', 'pixels', 'Position', panel_item_pos(0, 150, 1, 22),...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Style', 'ToggleButton',...
    'String', 'Darken Sulci',...
    'Value', 1,...
    'Callback', 'gpsr_menu_cortex');

% Shading
state.menu.cortex.shading = uicontrol(state.menu.cortex.panel,...
    'Units', 'pixels', 'Position', panel_item_pos(0, 175, 1, 22),...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Style', 'ToggleButton',...
    'String', 'Shading',...
    'Value', 1,...
    'Callback', 'gpsr_menu_cortex');

%% Timecourses Panel

% Panel
state.menu.timecourses.panel = uipanel(state.menu.fig,...
    'Units', 'pixels', 'Position', state.position.panel,...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Title', 'Timecourses');

%% Overlays Panel

% Panel
state.menu.overlays.panel = uipanel(state.menu.fig,...
    'Units', 'pixels', 'Position', state.position.panel,...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Title', 'Overlays');

%% Centroids Panel

% Panel
state.menu.centroids.panel = uipanel(state.menu.fig,...
    'Units', 'pixels', 'Position', state.position.panel,...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Title', 'Centroids');

%% Regions Panel

% Panel
state.menu.regions.panel = uipanel(state.menu.fig,...
    'Units', 'pixels', 'Position', state.position.panel,...
    'BackgroundColor', bg_color, 'FontSize', 10,...
    'Title', 'Regions');

%% Initialize lists

% Cortex.Study list from userstudies.mat 
user = getenv('USER');
userstudies = sprintf('%s/parameters/GPS/userstudies.mat', state.dir);
if(exist(userstudies, 'file'))
    userstudies = load(userstudies);
    if(isfield(userstudies, user))
        studies = userstudies.(user);
    end
end

% If failed, get it by scanning the parameter directory
if(~exist('studies', 'var'))
    studies = dir(sprintf('%s/parameters', state.dir));
    studies = {studies.name};
    studies(strcmp('.', studies) | strcmp('..', studies) | strcmp('GPS', studies)) = [];
end

% If there is no parameter directory, get it from somewhere else?

% Set the study list
set(state.menu.cortex.study, 'String', studies);

% Try to load from the parameters list
% If the parameters don't exist, then load from parameters.txt - which is
% something I should make

%% Save and do functions

% Save the state
gpsr_set(state)

% Configure the sub-menus
gpsr_menu_cortex




end % function