function gpsa_init_fig
% Initializes figure components for GPS: Analysis
%
% Author: Alexander Conrad Nied (anied@cs.washington.edu)
%
% Changelog:
% 2012-09-17 Created
% 2012-09-19 Added callbacks and override toggle
% 2012-09-21 Added stage, function, and queue functionality
% 2012-09-26 Removed stage, function, queue, and buttons
% 2012-09-27 Added button-based stage and function areas
% 2012-10-03 Added stage gpsa_do callback and fleshed out tag
% 2012-11-05 Modified height parameter
% 2013-04-25 GPS1.8 Changed subset design to condition hierarchy
% 2013-06-11 Refresh status now also re-investigates the status
% 2013-06-18 Cleaning up declarations a bit
% 2014-01-06 GPS1.9 Momentarily removed PLV stage

state = gpsa_get;

%% Draw the main GUI figure and set properties
h = 520; % Height of the GUI
state.gui.bgcolor = [0.8 0.8 0.8];
state.gui.position.fig = [100, state.gui.position.screen(4) - 100 - 480, 400, h];
clf(state.gui.fig)
set(state.gui.fig, 'Name', 'GPSa',...
    'Visible', 'on', 'NumberTitle', 'off',...
    'Units', 'pixels', 'Position', state.gui.position.fig,...
    'MenuBar', 'none', 'ToolBar', 'none',...
    'Color', state.gui.bgcolor);

% Draw the title
state.gui.title = uicontrol(state.gui.fig, 'Style', 'Text',...
    'Units', 'pixels', 'Position', [140, h - 480 + 440, 120, 25],...
    'BackgroundColor', state.gui.bgcolor,...
    'String', 'GPS: Analysis', 'FontSize', 14);

%% Study Area

% Title
state.gui.study_title = uicontrol(state.gui.fig, 'Style', 'Text',...
    'Units', 'pixels', 'Position', [20, h - 480 + 410, 80, 20],...
    'BackgroundColor', state.gui.bgcolor,...
    'String', 'Studies', 'FontSize', 10);

% List
state.gui.study_list = uicontrol(state.gui.fig, 'Style', 'Listbox',...
    'Units', 'pixels', 'Position', [20, h - 480 + 290, 80, 120],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', {'STUDY1', 'STUDY2', 'STUDY3'},...
    'Callback', 'gpsa_load_study; gpsa_color_compute;');

% New
state.gui.study_new = uicontrol(state.gui.fig, 'Style', 'PushButton',...
    'Units', 'pixels', 'Position', [20, h - 480 + 260, 40, 20],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', 'New', 'Callback', 'gpsa_new_study;');

% Edit
state.gui.study_edit = uicontrol(state.gui.fig, 'Style', 'PushButton',...
    'Units', 'pixels', 'Position', [60, h - 480 + 260, 40, 20],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', 'Edit', 'Callback', 'gpsa_edit_study;');

%% Subject Area

% Title
state.gui.subject_title = uicontrol(state.gui.fig, 'Style', 'Text',...
    'Units', 'pixels', 'Position', [140, h - 480 + 410, 80, 20],...
    'BackgroundColor', state.gui.bgcolor,...
    'String', 'Subjects', 'FontSize', 10);

% List
state.gui.subject_list = uicontrol(state.gui.fig, 'Style', 'Listbox',...
    'Units', 'pixels', 'Position', [120, h - 480 + 290, 120, 120],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', {'STUDY1_01', 'STUDY1_02', 'STUDY1_03'}, 'Max', 100,...
    'Callback', 'gpsa_load_subject; gpsa_color_compute;');

% New
state.gui.subject_new = uicontrol(state.gui.fig, 'Style', 'PushButton',...
    'Units', 'pixels', 'Position', [120, h - 480 + 260, 40, 20],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', 'New', 'Callback', 'gpsa_new_subject;');

% Edit
state.gui.subject_edit = uicontrol(state.gui.fig, 'Style', 'PushButton',...
    'Units', 'pixels', 'Position', [160, h - 480 + 260, 40, 20],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', 'Edit', 'Callback', 'gpsa_edit_subject;');

% All
state.gui.subject_all = uicontrol(state.gui.fig, 'Style', 'PushButton',...
    'Units', 'pixels', 'Position', [200, h - 480 + 260, 40, 20],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', 'All', 'Callback',...
    'state = gpsa_get; subjects = get(state.gui.subject_list, ''String''); set(state.gui.subject_list, ''Value'', 1:length(subjects)); gpsa_load_subject; gpsa_color_compute;');

%% Condition Area

% Title
state.gui.condition_title = uicontrol(state.gui.fig, 'Style', 'Text',...
    'Units', 'pixels', 'Position', [280, h - 480 + 410, 80, 20],...
    'BackgroundColor', state.gui.bgcolor,...
    'String', 'Conditions', 'FontSize', 10);

% List
state.gui.condition_list = uicontrol(state.gui.fig, 'Style', 'Listbox',...
    'Units', 'pixels', 'Position', [260, h - 480 + 290, 120, 120],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', {'<html><b>COND1</b><html>', '<html><b>COND2</b></html>', 'COND3', 'COND4'},...
    'Max', 100, 'Callback', 'gpsa_load_condition; gpsa_color_compute;');

% New
state.gui.subject_new = uicontrol(state.gui.fig, 'Style', 'PushButton',...
    'Units', 'pixels', 'Position', [260, h - 480 + 260, 40, 20],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', 'New', 'Callback', 'gpsa_new_condition;');

% Edit
state.gui.subject_edit = uicontrol(state.gui.fig, 'Style', 'PushButton',...
    'Units', 'pixels', 'Position', [300, h - 480 + 260, 40, 20],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', 'Edit', 'Callback', 'gpsa_edit_condition;');

% All
state.gui.subject_all = uicontrol(state.gui.fig, 'Style', 'PushButton',...
    'Units', 'pixels', 'Position', [340, h - 480 + 260, 40, 20],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', 'All', 'Callback',...
    'state = gpsa_get; conditions = get(state.gui.condition_list, ''String''); set(state.gui.condition_list, ''Value'', 1:length(conditions)); gpsa_load_condition; gpsa_color_compute;');

%% Stage Buttons

% Title
state.gui.stage_title = uicontrol(state.gui.fig, 'Style', 'Text',...
    'Units', 'pixels', 'Position', [40, h - 480 + 225, 80, 20],...
    'BackgroundColor', state.gui.bgcolor,...
    'String', 'Stages', 'FontSize', 10);

stage_list = gps_presets('stagenames');
stage_tags = gps_presets('stages');

for i = 1:length(stage_tags)
    tag = stage_tags{i};
    callback = sprintf('state = gpsa_get; state.stage = ''%s''; gpsa_set(state); gpsa_load_stage;', tag);
    
    % Main stage button
    name = sprintf('s%d_button', i);
    fulltag = sprintf('gpsa_%s', tag);
    state.gui.(name) = uicontrol(state.gui.fig,...
        'Style', 'PushButton', 'Callback', callback,...
        'Units', 'pixels', 'Position', [40, h - 480 + 230 - 25 * i, 80, 20],...
        'BackgroundColor', state.gui.bgcolor,...
        'String', stage_list{i}, 'Tag', fulltag);
    
    % Axes showing stage progress
    name = sprintf('s%d_status', i);
    state.gui.(name) = axes; %#ok<LAXES>
    set(state.gui.(name), 'Units', 'pixels',...
        'Position', [121, h - 480 + 231 - 25 * i, 48, 18]);
    imshow(cat(3, zeros(10, 10), zeros(10, 10), zeros(10, 10)), 'Parent', state.gui.(name));
    axis(state.gui.(name), 'normal');
    axis(state.gui.(name), 'off');
end

% Initialize first stage
state.stage = 'util';

%% Function Area

state.gui.function_title = uicontrol(state.gui.fig, 'Style', 'Text',...
    'Units', 'pixels', 'Position', [210, h - 480 + 225, 120, 20],...
    'BackgroundColor', state.gui.bgcolor,...
    'String', 'Functions', 'FontSize', 10);

% Other function buttons are initialized with gpsa_load_stage

%% Buttons

state.override = 0;
state.gui.override = uicontrol(state.gui.fig, 'Style', 'Checkbox',...
    'Units', 'pixels', 'Position', [20, h - 480 + 20, 100, 20],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', '   Redo',...
    'Callback', 'state = gpsa_get; state.override = get(state.gui.override, ''Value''); gpsa_set(state); if(state.autocolor); gpsa_color_compute; end');

state.autocolor = 0;
state.gui.autocolor = uicontrol(state.gui.fig, 'Style', 'Checkbox',...
    'Units', 'pixels', 'Position', [20, h - 480, 140, 20],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', '   Refresh Status',...
    'Callback', 'state = gpsa_get; state.autocolor = get(state.gui.autocolor, ''Value''); gpsa_set(state); if(state.autocolor); gpsa_color_compute; end');

state.gui.settings = uicontrol(state.gui.fig, 'Style', 'PushButton',...
    'Units', 'pixels', 'Position', [320, h - 480 + 445, 60, 20],...
    'BackgroundColor', state.gui.bgcolor, 'FontSize', 10,...
    'String', 'Settings',...
    'Callback', 'gpsa_settings;');

%% Save State and Initialize Compoments

gpsa_set(state);

gpsa_init_studies;

gpsa_load_stage;

end % function