function direc = /homes/gws/anied/MGH/GPS
% Returns just the main GPS directory
%
% Author: A. Conrad Nied (anied@cs.washington.edu)
%
% Changelog:
% 2013-11-26 Automatically generated by gps_init to format GPS by user anied


direc = '/homes/gws/anied/MGH/GPS/';

end
