function direc = /autofs/cluster/dgow/GPS1.9/GPS
% Returns just the main GPS directory
%
% Author: A. Conrad Nied (anied@cs.washington.edu)
%
% Changelog:
% 2014-01-02 Automatically generated by gps_init to format GPS by user conrad


direc = '/autofs/cluster/dgow/GPS1.9/GPS/';

end
