function direc = /Users/tomfool/tech/19/gow/GPS
% Returns just the main GPS directory
%
% Author: Alexander Conrad Nied (anied@cs.washington.edu)
%
% Changelog:
% 2019-01-08 Automatically generated by gps_init to format GPS by user tomfool


direc = '/Users/tomfool/tech/19/gow/GPS/';

end
